line_length:
  warning: 300
  error: 400
  ignores_comments: true
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - BuildTools
  - .idea
identifier_name:
  excluded:
    - id
    - to
type_name:
  excluded:
    - ID
