name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
      name: Run RandomApp iOS Unit tests
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Cache package swift
          uses: actions/cache@v2
          with:
            path: |
              BuildTools/.build/x86_64-apple-macosx
              BuildTools/.build/release
            key: ${{ runner.os }}-spm-v1-${{ hashFiles('BuildTools/Package.resolved') }}
        - name: Run swiftformat lint
          run: | 
            if [[ -f ./BuildTools/.build/release/swiftformat ]]; then
              ./BuildTools/.build/release/swiftformat --lint .
            else
              swift run -c release --package-path BuildTools swiftformat --lint .
            fi
        - name: Run swiftlint
          run: | 
            if [[ -f ./BuildTools/.build/release/swiftlint ]]; then
              ./BuildTools/.build/release/swiftlint lint --strict .
            else
              swift run -c release --package-path BuildTools swiftlint lint --strict .
            fi
        - name: Run tests
          run: set -o pipefail && xcodebuild test -scheme RandomApp -project RandomApp.xcodeproj  -destination 'platform=iOS Simulator,name=iPhone 12' 2>&1 | xcpretty --color --report junit
        - name: Publish iOS Unit Test Results
          uses: EnricoMi/publish-unit-test-result-action/composite@v1
          if: always()
          with:
            files: build/reports/*.xml
            check_name: RandomApp iOS Unit Tests
